### ISSUE TITLE
Is it Necessary to have all Images of same size that is for example a*a or a*b or b*a

### ISSUE THREAD

**Issue by deepkshikha** [KleinYuan/easy-yolo#4]

**Comment by KleinYuan** [comment]
@deepkshikha For yolo1, 416 * 416

**Comment by deepkshikha** [comment]
Thanks For response Done the Modification Still getting the error
![capture5](https://user-images.githubusercontent.com/13184577/33042931-951fa32c-ce69-11e7-8e42-fd5b83c38a2a.JPG)

**Comment by KleinYuan** [comment]
@deepkshikha Your errors say that it cannot load the image.

**Comment by KleinYuan** [comment]
Duplicate to another [issue](https://github.com/KleinYuan/easy-yolo/issues/5)
