### ISSUE TITLE
How to save bounding boxes and display it

### ISSUE THREAD

**Issue by deepkshikha** [KleinYuan/easy-yolo#6]
![result2](https://user-images.githubusercontent.com/13184577/33196109-54a5b39e-d103-11e7-8c53-05f88dd99206.JPG)
After training if make test is done the result is appearing as below 
![result](https://user-images.githubusercontent.com/13184577/33196059-f8fcf21e-d102-11e7-84c2-4769247493dd.JPG)

what is x and y here and why no bounding box is appearing

**Comment by KleinYuan** [comment]
@deepkshikha that you need to add logs in the src code

**Comment by deepkshikha** [comment]
I just need to move train.logs to Inside src folder or do anything else ?

**Comment by deepkshikha** [comment]
![ask](https://user-images.githubusercontent.com/13184577/33227926-839c122a-d1d4-11e7-9e72-53351451e2a4.JPG)


Are you talking about this logs which formed inside .git ?? I have to place this inside src folder or anything else

**Comment by deepkshikha** [comment]
Or u mean to add logs in code to test what happens wrong???

**Comment by KleinYuan** [comment]
Yes

**Comment by deepkshikha** [comment]
![testing time error](https://user-images.githubusercontent.com/13184577/33467594-9115c8aa-d67b-11e7-8446-7bf16bf10433.JPG)


It's still not working

**Comment by deepkshikha** [comment]
Do we need to change path anywhere or just put test.png in easy-yolo directory

**Comment by deepkshikha** [comment]
#KleinYuan You can close this issue . It's working for me now I am able to test. Thank you
