### ISSUE TITLE
cuda_runtime.h : No such file or directory

### ISSUE THREAD

**Issue by soheekk** [KleinYuan/easy-yolo#7]
Hello 
my machine and environment is
8 CPU
Quadro M4000 GPU
30 GB RAM
50 GB SSD
Ubuntu 14.04
OpenCV v2.4.8
CUDA 8.0.61-1
cuDNN 5.1.10-1+cuda8.0

and When I try to create a darknet executable (step 5.b) ,
![kakaotalk_20180104_010757053](https://user-images.githubusercontent.com/35074842/34532231-c0aae284-f0f8-11e7-9ec7-5b360c41daf8.png)

there is some error : cuda_runtime.h : No such file or directory

what is the problem? I really need your help...

**Comment by KleinYuan** [comment]
@soheekk it looks like your CUDA env didn't setup correctly.
Can you ensure that? (esp. environment variable set?)

Here's a good [reference](https://devtalk.nvidia.com/default/topic/1023902/cross-compile-samples-for-dpx2-4-1-8-0l_sdk-fails-with-quot-cuda_runtime-h-no-such-file-or-directory-quot-/).

**Comment by soheekk** [comment]
Thank you!!
you are right. My CUDA env didn't setup 
now I really setup corretly

Ubuntu 16.04
OpenCV v2.4.8
CUDA 8.0.61-1
cuDNN 5.1.10-1+cuda8.0

But new error has occured
![new_error_help_me](https://user-images.githubusercontent.com/35074842/34562054-05a1ce9c-f190-11e7-95da-e755a09755f4.png)
recipe for target 'obj/convolutional_layer.o'failed

Can it be a problem to switch to Ubuntu 16.04?
I will really appreciate your help....

**Comment by deepkshikha** [comment]
Set the path in .bashrc file for CUDNN  Add below three lines in your .bashrc file
export CUDA_HOME=/usr/local/cuda-8.0
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:$LD_LIBRARY_PATH
export PATH=${CUDA_HOME}/bin:${PATH}
It will remove your error

**Comment by soheekk** [comment]
Really thankful.  I removed the error !!
I could have successfully tested it!!
Really thank you...
I wish you a good day. thanks

**Comment by deepkshikha** [comment]
Have you tested ?? I am stuck in performing testing It's not predicticting anything. Training happened.

**Comment by soheekk** [comment]
yes!
I've tested it.
It was good performance!! Really thank you

**Comment by KleinYuan** [comment]
Good to know.
So we can close this issue then?

**Comment by deepkshikha** [comment]
#soheekk  I am not getting any boundary box while doing testing. Have you made any changes while you perform testing?

**Comment by deepkshikha** [comment]
#soheekk I am not getting any boundary box while doing testing. Have you made any changes while you perform testing?

**Comment by soheekk** [comment]
#KleinYuan Yes you can close this issue

#deepshikha No I didin't change anything. Maybe you need more training images.

**Comment by deepkshikha** [comment]
#soheekk How many training Images you have taken?

**Comment by soheekk** [comment]
#deepkshikha I taken 100 training images but result was good.
![predictions](https://user-images.githubusercontent.com/35074842/34676599-b42054d2-f4d0-11e7-8fbc-8964f688a63e.jpg)

+  I use Ubuntu 14.04 !!
In Ubuntu 16.04, It did not work well.

**Comment by deepkshikha** [comment]
Thanks Have you used GPU or CPU ?? I am using AWS GPU compute ubuntu 14.04 instance and further connecting it with vnc server for display. I have tried SSD and its working fine for me But YOLO is not getting any bounding box in my case I have trained 300 images.

**Comment by soheekk** [comment]
#deepkshikha I used GPU , (Quadro M4000)
I am using https://www.paperspace.com compute ubuntu 14.04 ML-in a Box ( Linux machine comes 
pre-installed CUDA 8.0.61-1 , cuDNN 5.1.10-1+cuda8.0 ,TensorFlow 1.2.1 (Python 2 & 3).... so you do not need to change anything.)

**Comment by deepkshikha** [comment]
#sohekk It worked in my local ubuntu system with CPU . Not working on AWS

**Comment by soheekk** [comment]
#deepkshikha congratulations! :D !!

**Comment by deepkshikha** [comment]
@soheekk
Thanku.

**Comment by deepkshikha** [comment]
#sohekk Do you know How to use test command for  testing folder of images instead of single image?
